# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Certs

on:
  schedule:
    - cron: "1 1 1 * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install certbot
      run: |
        sudo snap install core
        sudo snap install --classic certbot
        sudo ln -s /snap/bin/certbot /usr/bin/certbot
    - name: Generate cert
      env: 
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD}}
      run: |
        echo $FTP_PASSWORD > /tmp/out1.txt
        sudo certbot certonly -v --manual -d "dougschmittantiques.com" -d "*.dougschmittantiques.com" \
            --manual-auth-hook ${GITHUB_WORKSPACE}/update-dns.sh --manual-cleanup-hook ${GITHUB_WORKSPACE}/cleanup-dns.sh \
            -m sonofaforester@gmail.com --agree-tos --no-eff-email --manual-public-ip-logging-ok --preferred-challenges=dns
    - name: Install Cert
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD}}
      run: |
        echo dsaadmin:$FTP_PASSWORD >> /tmp/out1.txt
        
        sudo csplit -f cert- /etc/letsencrypt/live/dougschmittantiques.com/fullchain.pem '/-----BEGIN CERTIFICATE-----/' '{*}'
        
        sudo curl -v --get 'https://server3.iqnecthosting.com:2083/execute/SSL/install_ssl' \
            --data-urlencode cert@cert-01 \
            --data-urlencode key@/etc/letsencrypt/live/dougschmittantiques.com/privkey.pem \
            --data "domain=dougschmittantiques.com" \
            -u "dsaadmin:$FTP_PASSWORD"
                        
    - name: Logs
      if: always()
      run: |
        sudo cat /tmp/out1.txt
        sudo cat /var/log/letsencrypt/letsencrypt.log
        sudo cat /etc/letsencrypt/live/dougschmittantiques.com/fullchain.pem
        sudo cat /etc/letsencrypt/live/dougschmittantiques.com/privkey.pem
