# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Certs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install certbot
      run: |
        sudo snap install core
        sudo snap install --classic certbot
        sudo ln -s /snap/bin/certbot /usr/bin/certbot
    - name: Generate cert
      env: 
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD}}
      run: |
        echo $FTP_PASSWORD > /tmp/out1.txt
       # sudo certbot certonly -v --manual -d "cert.dougschmittantiques.com" \
       #     --manual-auth-hook ${GITHUB_WORKSPACE}/update-certs.sh -m sonofaforester@gmail.com \
       #     --agree-tos --no-eff-email --manual-public-ip-logging-ok
    - name: Install Cert
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD}}
      run: |
        echo dsaadmin:$FTP_PASSWORD >> /tmp/out1.txt
        
        csplit -f cert- {GITHUB_WORKSPACE}/full.full '/-----BEGIN CERTIFICATE-----/' '{*}'
        
        sudo curl --get 'https://server3.iqnecthosting.com:2083/execute/SSL/install_ssl' \
            --data-urlencode cert@{GITHUB_WORKSPACE}/cert-01 \
            --data-urlencode key@{GITHUB_WORKSPACE}/pri.pri \
            --data "domain=cert.dougschmittantiques.com"
            -u dsaadmin:$FTP_PASSWORD
            
          #  --data-urlencode cert@/etc/letsencrypt/live/cert.dougschmittantiques.com/fullchain.pem \
          #  --data-urlencode key@/etc/letsencrypt/live/cert.dougschmittantiques.com/privkey.pem \
            
    - name: Logs
      if: always()
      run: |
        sudo cat /tmp/out1.txt
        sudo cat /var/log/letsencrypt/letsencrypt.log
        sudo cat /etc/letsencrypt/live/cert.dougschmittantiques.com/fullchain.pem
        sudo cat /etc/letsencrypt/live/cert.dougschmittantiques.com/privkey.pem
